12.0 fix various invoicing policy
grap/grap-odoo-custom pull request #123
Opened 2020-11-11 16:18 UTC by legalsylvain

2020-11-11 21:35 UTC, quentinDupont requested changes
'tin mais c'est du costum la gestion de l'invoice policy des products..

2020-11-11 21:35 UTC, quentinDupont commented on grap_change_views_product/models/product_template.py
> +        print("OVERWRITE::_compute_invoice_policy")
tu veux laisser le print ?

2020-11-11 21:39 UTC, legalsylvain commented on grap_change_views_product/models/product_template.py
> +        print("OVERWRITE::_compute_invoice_policy")
ouais je trouvais ça joli, mais je vais l'enlever. Toi et Travis vous êtes pas d'accord. c'est la démocratie.

2020-11-11 21:41 UTC, legalsylvain commented
> 'tin mais c'est du costum la gestion de l'invoice policy des products..

Alors en fait, le module de base de sale est daubé. le module sale_invoice_policy (de l'OCA) essaye de rattraper le truc, mais c'est daubé. Total, notre base de données est toute pourri.
En vérité, je crois le seul truc dont on a besoin c'est : lors de la facturation : 

- si c'est un produit service alors on se base sur la commande, sinon ça merde systématiquement (vu que y'a rien de livré)
- sinon (stockable / consommable) on se base sur ce qui est paramétré sur le sale order.

2020-11-12 11:25 UTC, quentinDupont commented
> > 'tin mais c'est du costum la gestion de l'invoice policy des products..
> 
> Alors en fait, le module de base de sale est daubé. le module sale_invoice_policy (de l'OCA) essaye de rattraper le truc, mais c'est daubé. Total, notre base de données est toute pourri.
> En vérité, je crois le seul truc dont on a besoin c'est : lors de la facturation :
> 
>     * si c'est un produit service alors on se base sur la commande, sinon ça merde systématiquement (vu que y'a rien de livré)
> 
>     * sinon (stockable / consommable) on se base sur ce qui est paramétré sur le sale order.
> 
> 
> je peux rajouter un truc dans la roadmap, genre "à rechecker à tete reposée". ;-)

simple et efficace ('fin faut que je teste) ce code en tout cas !

2020-11-12 11:25 UTC, quentinDupont approved these changes

2020-11-13 19:40 UTC, legalsylvain commented
(branche déployée le 11/11 soir)

travis A fixer, avant merge.

2020-12-08 10:33 UTC, legalsylvain commented
/ocabot merge patch

2020-12-08 13:47 UTC, merged