[IMP] Payment : remove useless fields for grap
grap/grap-odoo-custom pull request #163
Opened 2021-05-03 15:17 UTC by quentinDupont

Avant 
![image](https://user-images.githubusercontent.com/9005817/116895180-35272700-ac33-11eb-9885-569161bd83d6.png)
Après
![image](https://user-images.githubusercontent.com/9005817/116895221-3eb08f00-ac33-11eb-8625-356494984f9a.png)

#

2021-05-13 20:48 UTC, legalsylvain commented
Yop.

ça fait sens. ceci étant je crains les effets de bord, lié au fait que account.payment contient des paiements fournisseurs en prod.
la valeur ``outbound`` va devenir invalide. je sais pas trop ce que ça entraine. t'as testé sur une base grap ? 

```
 payment_type | count  
--------------+--------
 inbound      | 166802
 outbound     |  25342
```

2021-05-17 13:17 UTC, quentinDupont commented
Yes testé sur base grap : en tant que manager, on accède encore au menu de paiement fournisseur, donc là ça renvoie une erreur.
Mais en tant qu'acti, iels ont pas accès à ce menu donc pas d'erreur.
Les paiements outbound sont soit des vieux trucs, soit des erreurs pour moi.

En tout cas avec mes tests, ça ne m'a pas empêché de faire des paiements clients

2021-06-03 09:09 UTC, legalsylvain requested changes
yop. du coup, je suis pas super chaud sur cette modif dans son design. 
(j'ai jamais vu ça dans l'OCA, et j'ai peur d'effet de bord).

si on veut intégrer cette sécurité, on peut peut etre le faire avec un truc genre : 

api@constrain("payment_type")
def _check_payment_type(self):
if l'utilisateur n'est pas membre du groupe compta / manager:
raise UseError("vous n'avez pas le droit de saisir un paiement autre que client")

- ça sécurise, c'est plus dans l'idée
- bémol : on voit encore les options inutiles.


t'en penses quoi ?

2021-06-03 14:57 UTC, quentinDupont commented
> yop. du coup, je suis pas super chaud sur cette modif dans son design.
> (j'ai jamais vu ça dans l'OCA, et j'ai peur d'effet de bord).
> 
> si on veut intégrer cette sécurité, on peut peut etre le faire avec un truc genre :
> 
> api@constrain("payment_type")
> def _check_payment_type(self):
> if l'utilisateur n'est pas membre du groupe compta / manager:
> raise UseError("vous n'avez pas le droit de saisir un paiement autre que client")
> 
>     * ça sécurise, c'est plus dans l'idée
> 
>     * bémol : on voit encore les options inutiles.
> 
> 
> t'en penses quoi ?

J'en pense que je suis d'accord, un peu trop osé de faire un truc qu'on voit nul part, surement des effets de bords.
Si le champ de sélection était calculé avec une fonction on aurait pu surchargé mais pô là

Du coup jsuis parti sur ton idée :)

2021-06-03 17:52 UTC, legalsylvain approved these changes
Top ! DEsolé pour la frilosité sur le 1er design.

2021-06-04 07:03 UTC, quentinDupont commented
> Top ! DEsolé pour la frilosité sur le 1er design.

Ne le soit pas, j'ai compris :)

2021-06-13 14:23 UTC, legalsylvain commented
/ocabot merge patch

MeP 10/06/2021

2021-06-16 09:51 UTC, legalsylvain commented
/ocabot merge patch

MeP 10/06/2021

2021-06-16 10:25 UTC, merged