[WIP] Grap MRP
grap/grap-odoo-custom pull request #166
Opened 2021-05-17 14:24 UTC by quentinDupont

2021-06-03 09:30 UTC, legalsylvain requested changes
1) cool ! 

2) il manque une dépendance OCA le module ``mrp_bom_component_menu`` n'est pas trouvé.

3) on merge non ? (c'est un module de dév, mais autant qu'il soit dispo).

2021-06-04 08:46 UTC, quentinDupont commented
>     1. cool !
> 
>     2. il manque une dépendance OCA le module `mrp_bom_component_menu` n'est pas trouvé.
> 
>     3. on merge non ? (c'est un module de dév, mais autant qu'il soit dispo).

allez !

2021-06-04 09:27 UTC, legalsylvain approved these changes

2021-06-24 11:51 UTC, legalsylvain commented
MeP du 23/06/2021

/ocabot merge patch

2021-06-24 12:27 UTC, merged