WIP - grap activity became res company
grap/grap-odoo-custom pull request #174
Opened 2021-05-28 15:18 UTC by quentinDupont

- Remove grap activity model → became res.company
- kanban view imitate old kanban view
- new form view
- new fields on res.company

Grap : apps/deck/#/board/144/card/1267

2021-06-01 20:57 UTC, legalsylvain commented on grap_cooperative/models/res_company.py
> +    is_using_Odoo = fields.Boolean(
yop ! plutot en minuscule les noms par convention. ``is_using_odoo``

2021-06-22 15:12 UTC, legalsylvain reviewed
qq remarques.

sinon, de façon plus général : 
- dans le menu, vu qu'il y a moins d'item, je mettrais bien au niveau 1 les éléments "Collèges" et mandats" pour qu'il soit plus visible.
- le modèle ``grap.category`` est supprimé avec cette PR. est-ce qu'on ne créerait pas un élément de menu avec une vue sur ``res.company.category`` ? (qui peut ou prou est la même chose).

2021-06-22 15:12 UTC, legalsylvain commented on grap_cooperative/demo/grap_people.xml
> +        <field name="street">Street Ambroise Croizat</field>
héhé.

2021-06-22 15:12 UTC, legalsylvain commented on grap_cooperative/migrations/12.0.2.0.0/pre-migration.py
> +        WHERE res_company.name ILIKE ('%' || ga.activity_name || '%');
``WHERE res_company.code = ga.code`` serait peut-être plus prédictif, et moins sujet aux aléat de fautes d'ortographe, ou d'accent ?

2021-06-22 15:12 UTC, legalsylvain commented on grap_cooperative/models/grap_people.py
> +    def _handle_name(self):
pas compris. on peut en causer ?

2021-06-22 15:12 UTC, legalsylvain commented on grap_cooperative/models/grap_people.py
> +        self.write({"company_id": False})
pourquoi ?

2021-06-22 15:12 UTC, legalsylvain commented on grap_cooperative/models/res_company.py
> +    display_name = fields.Char(
ce champs existe déjà dans Odoo (res.company.display_name). peut-etre que pour éviter les conflits, ça serait chouette de mettre plutôt un champ ``clean_name``.

2021-06-22 15:12 UTC, legalsylvain commented on grap_cooperative/models/res_company.py
> +    # manager_ids = fields.Many2many(
ligne 111 à 135 : ça a vocation a être décommenté ? ou on peut shooter ?

2021-06-22 15:20 UTC, legalsylvain requested changes
la migration des liens utilisateurs -> res.company est cassé. Cf 3PP, BSG.

2021-06-25 13:43 UTC, quentinDupont commented
> qq remarques.
> 
> sinon, de façon plus général :
> 
>     * dans le menu, vu qu'il y a moins d'item, je mettrais bien au niveau 1 les éléments "Collèges" et mandats" pour qu'il soit plus visible.
> 
>     * le modèle `grap.category` est supprimé avec cette PR. est-ce qu'on ne créerait pas un élément de menu avec une vue sur `res.company.category` ? (qui peut ou prou est la même chose).

Bonnes idées !
J'ai fait les deux :heavy_check_mark:

2021-06-25 14:23 UTC, quentinDupont commented on grap_cooperative/models/grap_people.py
> +        self.write({"company_id": False})
grap_member ça n'existe plus du coup
c'est direct grap.people → res.company

Et du coup j'ai changé le nom car le but n'est plus de supprimer mais juste de détacher le lien entre people et company (je me dis qu'on a envie de garder la fiche des grap.people même si la personne part de l'activité (au cas où elle revient dans une autre acti par exemple))

2021-06-25 14:37 UTC, quentinDupont commented on grap_cooperative/models/res_company.py
> +    display_name = fields.Char(
gravos daccoros

2021-06-25 14:43 UTC, quentinDupont commented on grap_cooperative/models/res_company.py
> +    # manager_ids = fields.Many2many(
a shooté

2021-06-25 14:57 UTC, quentinDupont commented on grap_cooperative/migrations/12.0.2.0.0/pre-migration.py
> +        WHERE res_company.name ILIKE ('%' || ga.activity_name || '%');
au top , bien plus simple en effet !

2021-06-25 14:57 UTC, quentinDupont commented on grap_cooperative/models/grap_people.py
> +        self.write({"company_id": False})
> la migration des liens grap.people -> res.company est cassé. Cf 3PP, BSG.

du coup j'ai plus la base de test pour voir ça hmm. P-e que ça passera mieux avec la modif sur le script de migration

2021-06-25 14:58 UTC, quentinDupont commented
> la migration des liens grap.people -> res.company est cassé. Cf 3PP, BSG.

du coup j'ai plus la base de test pour voir ça hmm. P-e que ça passera mieux avec la modif sur le script de migration

2021-07-20 12:56 UTC, legalsylvain commented on grap_cooperative/models/grap_people.py
> +        self.write({"company_id": False})
:+1:

2021-07-20 15:07 UTC, legalsylvain commented
Yop. J'ai fait un gros commit là : https://github.com/grap/grap-odoo-custom/pull/174/commits/5da5b362bf04d9bcaba15f7a61ae94bf8d170634

- [MIG] initialize res_company.is_displayed_in_directory  from grap_activity.state
- [FIX] fix migration. (link between grap_people and res_company). Base script on code.
- [REF] temporary remove accounting_closing_date.
- [ADD] correct security access for the crew members
- [UPD] translation
- [FIX] set correct context in the company_id field, to display correct form view
- [REF] remove useless code
- [ADD] private phone on people kanban view

voilou.

2021-07-20 15:16 UTC, legalsylvain approved these changes

2021-07-30 07:32 UTC, legalsylvain commented
MeP du 28/07/2021.

/ocabot merge patch

2021-07-30 09:34 UTC, merged