[IMP] Simplify partner form view + inclusive language
grap/grap-odoo-custom pull request #248
Opened 2022-08-18 15:41 UTC by quentinDupont

Améliorations :
- onglet par défaut "Ventes et Achats"
- champs non utilisés cachés
- language inclusif
- homogénéisation du groups admin

![image](https://user-images.githubusercontent.com/9005817/185436817-7e34282e-9c4e-4fc8-9a14-939d8f70eb00.png)

2022-09-06 15:37 UTC, legalsylvain approved these changes
qq remarques mineures ! 

sinon, ça a l'air good !  merci

2022-09-06 15:37 UTC, legalsylvain commented on grap_change_views_partner/views/view_res_partner_form.xml
> +              <attribute name="placeholder">Région</attribute>
```suggestion
              <attribute name="placeholder">Region</attribute>
```

2022-09-06 15:37 UTC, legalsylvain commented on grap_change_views_partner/views/view_res_partner_form.xml
> +              <attribute name="string">Est&#160;un·e&#160;Client·e</attribute>
english !

2022-09-06 15:37 UTC, legalsylvain commented on grap_change_views_partner/views/view_res_partner_form.xml
> +              <attribute name="string">Est&#160;un·e&#160;Fournisseur·e</attribute>
english !

2022-09-06 15:37 UTC, legalsylvain commented on grap_change_views_partner/static/src/scss/grap_change_views_partner.scss
> +}
nitpicking. 
j'ai l'impression que ça va changer des trucs dans tout odoo ça, non ? 

du coup, peut-etre le mêtre plutot dans grap_change_views_base ou un truc comme ça...

2022-09-06 15:37 UTC, legalsylvain commented on grap_change_views_partner/views/view_res_partner_tree.xml
> +                <field name="zip" string="Code&#160;postal"/>
english !

2022-09-06 15:37 UTC, legalsylvain commented on grap_change_views_partner/views/view_res_partner_tree.xml
> +  </template>
nitpicking. 

cette partie là doit aller dans un fichier dédié. ``./views/templates.xml``.

2022-09-06 15:37 UTC, legalsylvain commented on grap_change_views_partner/__manifest__.py
> +        "joint_buying_base",
pourquoi cette dépendance. (j'ai peut etre zappé un truc...)

2022-09-07 08:33 UTC, quentinDupont commented on grap_change_views_partner/__manifest__.py
> +        "joint_buying_base",
Jav, erreur à priori !

2022-09-07 08:35 UTC, quentinDupont commented on grap_change_views_partner/static/src/scss/grap_change_views_partner.scss
> +}
exact !

2022-09-08 09:45 UTC, legalsylvain commented on grap_change_views_partner/views/view_res_partner_tree.xml
> +            <tree editable="top">
Yop. est-ce que tu pourrais reverter ce changement ?  ``<tree editable="bottom">`` -> ``<tree editable="top">``

- ça conflict avec un autre changement de mouna. https://github.com/grap/grap-odoo-custom/pull/246/files
- je pense que si on fait ce changement là, il faudra le faire un peu partout.

il faut que
-  tu modifies
- tu fasse un git commit -a --fixup=a5358ee908ae7221c4e12f4dea2e4a1b25820e4d
- - git commit --rebase -i HEAD~5 --autosquash

merci ! 

(en attendant, je retire la PR de Mouna).

2022-09-09 10:18 UTC, quentinDupont commented on grap_change_views_partner/views/view_res_partner_tree.xml
> +            <tree editable="top">
thanks !

2022-09-09 10:26 UTC, quentinDupont commented
allez ça me semble bien autosquashé :)

2022-09-09 12:03 UTC, quentinDupont commented
@legalsylvain j'avais oublié un fichier --' je viens de push force en cleanant un peu les commits ;)

2022-09-09 13:34 UTC, legalsylvain requested changes
toujours pas ! j'arrive pas à comprendre, là pour le coup.
On attend la prochaine mep, où je push le code de mouna, et tu feras un rebase de la branche 12.0, qui devra résoudre le soucis je pense.
bise !

2022-09-12 07:51 UTC, quentinDupont commented
> toujours pas ! j'arrive pas à comprendre, là pour le coup. On attend la prochaine mep, où je push le code de mouna, et tu feras un rebase de la branche 12.0, qui devra résoudre le soucis je pense. bise !

ok !

2022-09-29 09:23 UTC, legalsylvain commented
/ocabot rebase

2022-11-15 14:24 UTC, legalsylvain commented
MeP du 14/11/2022

/ocabot merge patch

2022-11-15 14:36 UTC, merged