[ADD] view stock valuation
grap/grap-odoo-custom pull request #99
Opened 2020-10-24 10:06 UTC by quentinDupont

2020-10-24 12:42 UTC, legalsylvain requested changes

2020-10-24 12:42 UTC, legalsylvain commented on grap_change_views_product/i18n/fr.po
> +msgstr ""
Y'a des traductions qui ont l'air d'avoir sauté.
Sinon, le reste est cool !

2020-10-24 13:38 UTC, quentinDupont commented on grap_change_views_product/i18n/fr.po
> +msgstr ""
Quand c'est le même mot en anglais et en français, ça saute au moment de l'export du po.
Vu que ce sont les mêmes mots, c'est pas grave :)

2020-10-24 15:11 UTC, legalsylvain commented on grap_change_views_product/i18n/fr.po
> +msgstr ""
Ok ! Je savais pas. C'est cheloud ceci etant.

2020-10-24 15:13 UTC, legalsylvain commented
/ocabot merge patch

2020-10-24 15:35 UTC, merged

2020-10-25 07:35 UTC, legalsylvain commented
/ocabot merge patch